export const dmvLocationAreas: Record<string, string[]> = {
  AL: ["Montgomery", "Birmingham", "Mobile", "Huntsville", "Tuscaloosa"],
  AK: ["Anchorage", "Fairbanks", "Juneau", "Wasilla", "Soldotna"],
  AZ: ["Phoenix", "Tucson", "Mesa", "Glendale", "Scottsdale"],
  AR: ["Little Rock", "Fort Smith", "Fayetteville", "Jonesboro", "Pine Bluff"],
  CA: ["Los Angeles", "San Diego", "San Francisco", "Sacramento", "San Jose", "Fresno", "Oakland"],
  CO: ["Denver", "Aurora", "Colorado Springs", "Fort Collins", "Pueblo", "Grand Junction"],
  CT: ["Bridgeport", "Hamden", "Danbury", "Norwalk", "Waterbury", "Wethersfield", "Willimantic"],
  DE: ["Wilmington", "Dover", "Georgetown", "New Castle"],
  DC: ["Washington DC", "Georgetown Service Center", "Benning Ridge Service Center"],
  FL: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee", "Fort Lauderdale"],
  GA: ["Atlanta", "Marietta", "Lawrenceville", "Savannah", "Columbus", "Macon"],
  HI: ["Honolulu", "Kapolei", "Hilo", "Kailua-Kona", "Lihue"],
  ID: ["Boise", "Meridian", "Idaho Falls", "Pocatello", "Coeur d'Alene"],
  IL: ["Chicago", "Springfield", "Rockford", "Naperville", "Peoria"],
  IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Lafayette"],
  IA: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  KS: ["Wichita", "Topeka", "Overland Park", "Kansas City", "Salina"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Frankfort", "Paducah"],
  LA: ["Baton Rouge", "New Orleans", "Shreveport", "Lafayette", "Lake Charles"],
  ME: ["Augusta", "Portland", "Bangor", "Lewiston", "Scarborough"],
  MD: ["Baltimore", "Glen Burnie", "Gaithersburg", "Salisbury", "Waldorf", "Frederick"],
  MA: ["Boston", "Worcester", "Springfield", "Lowell", "Braintree"],
  MI: ["Detroit", "Grand Rapids", "Lansing", "Flint", "Kalamazoo"],
  MN: ["Minneapolis", "Saint Paul", "Duluth", "Rochester", "St. Cloud"],
  MS: ["Jackson", "Gulfport", "Hattiesburg", "Tupelo", "Southaven"],
  MO: ["St. Louis", "Kansas City", "Springfield", "Columbia", "Jefferson City"],
  MT: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
  NE: ["Omaha", "Lincoln", "Grand Island", "Kearney", "Norfolk"],
  NV: ["Las Vegas", "Reno", "Carson City", "Henderson", "Elko"],
  NH: ["Concord", "Manchester", "Nashua", "Dover", "Keene"],
  NJ: ["Newark", "Wayne", "Edison", "Trenton", "Cherry Hill"],
  NM: ["Albuquerque", "Santa Fe", "Las Cruces", "Roswell", "Farmington"],
  NY: ["Brooklyn", "Bronx", "Manhattan", "Queens", "Albany", "Buffalo", "Rochester", "Yonkers"],
  NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Asheville", "Fayetteville"],
  ND: ["Fargo", "Bismarck", "Grand Forks", "Minot", "Williston"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  OK: ["Oklahoma City", "Tulsa", "Norman", "Lawton", "Enid"],
  OR: ["Portland", "Salem", "Eugene", "Bend", "Medford"],
  PA: ["Philadelphia", "Pittsburgh", "Harrisburg", "Allentown", "Erie"],
  RI: ["Cranston", "Providence", "Woonsocket", "Warwick", "Middletown"],
  SC: ["Columbia", "Charleston", "Greenville", "Myrtle Beach", "Spartanburg"],
  SD: ["Sioux Falls", "Rapid City", "Pierre", "Aberdeen", "Watertown"],
  TN: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Murfreesboro"],
  TX: ["Austin", "Houston", "Dallas", "San Antonio", "Fort Worth", "El Paso"],
  UT: ["Salt Lake City", "Provo", "Ogden", "St. George", "Logan"],
  VT: ["Montpelier", "Burlington", "Rutland", "Bennington", "Springfield"],
  VA: ["Richmond", "Norfolk", "Fairfax", "Roanoke", "Virginia Beach"],
  WA: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Olympia"],
  WV: ["Charleston", "Huntington", "Morgantown", "Beckley", "Parkersburg"],
  WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Eau Claire"],
  WY: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
};

export function getDmvLocationAreas(stateCode?: string | null) {
  if (!stateCode) return [];
  return dmvLocationAreas[stateCode.toUpperCase()] ?? [];
}
